## defining working directory
wd: /g100_work/Gen4A_mulmy/

## references
refGen: /g100_work/Gen4A_mulmy/ref/genome.fa
gold_indels: /g100_work/Gen4A_mulmy/ref/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
gnomad_af: /g100_work/Gen4A_mulmy/ref/af-only-gnomad.hg38.vcf.gz

## bwa params ##
bwa_id: test

## read depth params ##
readCounterScript:  /hmmcopy_utils/bin/readCounter
chrs: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY
binSize: 1000000 # set window size to compute coverage

## ichorCNA params ##
ichorCNA_libdir: /ichorCNA/
# included in GitHub repo
ichorCNA_rscript:  /ichorCNA/scripts/runIchor.R
# use panel matching same bin size (optional)
ichorCNA_normalPanel: /ichorCNA/inst/extdata/HD_ULP_PoN_hg38_1Mb_median_normAutosome_median.rds
# must use gc wig file corresponding to same binSize (required)
ichorCNA_gcWig: /ichorCNA/inst/extdata/gc_hg38_1000kb.wig
# must use map wig file corresponding to same binSize (required)
ichorCNA_mapWig:  /ichorCNA/inst/extdata/map_hg38_1000kb.wig
# use bed file if sample has targeted regions, eg. exome data (optional)
ichorCNA_exons:  NULL
ichorCNA_centromere: /ichorCNA/inst/extdata/GRCh38.GCA_000001405.2_centromere_acen.txt
ichorCNA_minMapScore: 0.75
ichorCNA_chrs: c(1:22, 'X') #c(1:22)
ichorCNA_fracReadsInChrYForMale: 0.002
ichorCNA_genomeBuild:  hg38
ichorCNA_genomeStyle:  NCBI

# chrs used for training ichorCNA parameters, e.g. tumor fraction.
ichorCNA_chrTrain: c(1:22)
# non-tumor fraction parameter restart values; higher values should be included for cfDNA
ichorCNA_normal:  c(0.5,0.6,0.7,0.8,0.9,0.95)
# ploidy parameter restart values
ichorCNA_ploidy:  c(2) #c(2,3)
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
# states to use for subclonal CN
ichorCNA_scStates:  c(1,3)
# set maximum copy number to use
ichorCNA_maxCN:  5
# TRUE/FALSE to include homozygous deletion state
ichorCNA_includeHOMD: FALSE
# Exclude solutions if total length of subclonal CNAs > this fraction of the genome
ichorCNA_maxFracGenomeSubclone: 0.5
# Exclude solutions if total length of subclonal CNAs > this fraction of total CNA length
ichorCNA_maxFracCNASubclone: 0.7
# control segmentation - higher (e.g. 0.9999999) leads to higher specificity and fewer segments
# lower (e.g. 0.99) leads to higher sensitivity and more segments
ichorCNA_txnE:  0.9999
# control segmentation - higher (e.g. 10000000) leads to higher specificity and fewer segments
# lower (e.g. 100) leads to higher sensitivity and more segments
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  png
ichorCNA_plotYlim: c(-2,4)

## BOBaFIT params ##
BOBaFIT_libdir: /BOBaFIT/
BOBaFIT_rscript: /BOBaFIT/scripts/runBOBaFIT.R
BOBaFIT_normChr: c('1p','2p','2q','4p','4q','8p','10p','10q','12p','12q','16p','17p','17q','18p','18q') #1p,2p,2q,4p,4q,8p,8q,10p,10q,12p,12q,16p,17p,17q,18p,18q
BOBaFIT_refGenome: hg38
